-- File generated by the BNF Converter (bnfc 2.9.6.1).
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language LF3.
module AbsLF where

import qualified Data.String
import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Read, Show)

data Program = Prog [Function]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Function = Fun Type Ident [Decl] Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl = Dec Type Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
  = EComp Exp Exp -- Novo tipo de expressao: Composicao de expressoes
  | ELambda [Decl] Exp -- Novo tipo de expressao: expressao lambda
  | EIf Exp Exp Exp
  | EOr Exp Exp
  | EAnd Exp Exp
  | ENot Exp
  | ECon Exp Exp
  | EAdd Exp Exp
  | ESub Exp Exp
  | EMul Exp Exp
  | EDiv Exp Exp
  | ECall Exp [Exp]
  | EInt Integer
  | EVar Ident
  | EStr String
  | ETrue
  | EFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type = Tbool | Tint | TStr | TFun Type [Type]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)
