-- File generated by the BNF Converter (bnfc 2.9.6.1).
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language LF2.
module AbsLF where

import Data.Data as D (Data, Typeable)
import qualified Data.String
import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Read, Show)

data Program = Prog [Function]
  deriving (C.Eq, C.Ord, C.Show, C.Read, D.Data, D.Typeable)

data Function = Fun Type Ident [Decl] Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read, D.Data, D.Typeable)

data Decl = Dec Type Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, D.Data, D.Typeable)

data Exp
  = EIf Exp Exp Exp
  | EOr Exp Exp
  | EAnd Exp Exp
  | ENot Exp
  | ECon Exp Exp
  | EAdd Exp Exp
  | ESub Exp Exp
  | EMul Exp Exp
  | EDiv Exp Exp
  | ECall Ident [Exp]
  | EInt Integer
  | EVar Ident
  | EStr String
  | ETrue
  | EFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read, D.Data, D.Typeable)

data Type = Tbool | Tint | TStr | TFun Type [Type]
  deriving (C.Eq, C.Ord, C.Show, C.Read, D.Data, D.Typeable)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString, D.Data, D.Typeable)
